'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { Clock } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import {
  ACTIVITY_KEY,
  clearIdleActivity,
  idlePhase,
  inheritedActivity,
  markIdleActivity,
  sessionStartMs,
  SIGNED_OUT_KEY,
  TICK_MS,
  TIMEOUT_NOTICE,
  WRITE_THROTTLE_MS,
} from '@/lib/idle-timeout'
import { Button } from '@/components/ui/button'
import { Dialog } from '@/components/ui/dialog'

/**
 * Signs a member out after a period with no keyboard or pointer activity and sends them to
 * the login screen. Mounted once, by `app/(protected)/layout.tsx`, and only for a caller
 * who resolved to a user — so it never runs on the marketing site or the auth pages.
 *
 * WHY THIS IS NOT A CONFIG SETTING. `[auth.sessions] inactivity_timeout` in
 * `supabase/config.toml` looks like the same feature and cannot replace it:
 *
 *   * GoTrue measures inactivity as time since the session was last REFRESHED, and a
 *     client with `autoRefreshToken` on refreshes on a timer whether or not anybody is
 *     at the keyboard. So an open tab keeps its session fresh indefinitely and that
 *     setting never fires for the case this component exists for. Measured, not
 *     reasoned — see the note beside the setting.
 *   * It cannot navigate anybody. The session goes invalid and the tab keeps rendering
 *     the page it already has until something fails — which is the opposite of
 *     "return them to the login screen".
 *
 * The two are complements, not alternatives: this covers a human who walked away from an
 * open tab; the setting covers a browser that is not running at all.
 *
 * So the timer lives here, and it is a real sign-out rather than a redirect: when it
 * fires it calls `signOut({ scope: 'local' })`, which revokes this session server-side.
 * The cookie is not merely deleted.
 *
 * ── AND A PHONE DOES NOT KEEP A PAGE LOADED, WHICH USED TO DEFEAT IT ENTIRELY ─────
 * This section said "close the tab and come back tomorrow and the session is still valid,
 * because nothing was running to time it out", and treated that as the half
 * `inactivity_timeout` covers. On a phone it is not a corner: **mobile browsers evict
 * background tabs as a matter of routine**, so "the tab was discarded and reloaded" IS the
 * ordinary mobile session, and the feature never fired there at all. That was the report:
 * mobile does not automatically log you out.
 *
 * A discarded tab runs no timer, so the only thing that can notice is the MOUNT of the next
 * page load, reading the marker somebody's last activity left behind. That is
 * `inheritedActivity`, and it now answers three ways rather than two — adopt, expire, or
 * start fresh — with `sessionStartedAt` telling "this session's own stale marker" apart
 * from "residue from an earlier session". Its header carries the whole argument, including
 * why getting that discrimination wrong in one direction locks somebody out of a session
 * they have just created.
 *
 * Two further consequences live in this file:
 *
 *   * **The marker is written at MOUNT when this tab starts its own clock.** Without it a
 *     member who loads a page and reads it without touching anything leaves no trace at
 *     all, so the eviction above has nothing to expire against. It is written only in the
 *     `fresh` case — writing it after ADOPTING one would overwrite the older marker this
 *     tab was supposed to inherit, restarting the clock it just joined.
 *   * **Returning to a backgrounded tab re-checks immediately.** iOS suspends JavaScript in
 *     a background tab, so the interval below simply does not run while the phone is
 *     locked; it resumes on return and would expire within a second anyway. The explicit
 *     check on `visibilitychange`, `focus` and `pageshow` makes that instant instead, and
 *     covers a back-forward-cache restore where the timer's resumption is not guaranteed.
 *     Same three events `ShellWatcher` watches, and for the same reason: coming back to a
 *     tab is when a stale one is both most likely and most visible.
 *
 * It still measures idleness rather than absence, and it is still not
 * `inactivity_timeout`'s job — but "the browser was not running" is no longer a gap it
 * shrugs at, because on a phone that is most of the time.
 */

/**
 * The durations, the storage keys and the active/warn/expired boundary all live in
 * `lib/idle-timeout.ts` — including `IDLE_LIMIT_MS`, which is the one number anybody
 * changing this feature is looking for.
 */

/**
 * Pointer and keyboard only, deliberately. `mousemove` and `scroll` are generated by
 * momentum scrolling, by a nudged desk and by an animated page, so including them makes
 * the timeout unreliable in the one direction that matters — never firing. A message
 * arriving in a chat room is not activity either: the point is somebody at the keyboard.
 */
const ACTIVITY_EVENTS = ['pointerdown', 'keydown', 'touchstart', 'wheel'] as const

export function IdleTimeout({ sessionStartedAt }: {
  /**
   * `user.last_sign_in_at`, resolved on the SERVER by `app/(protected)/layout.tsx`.
   *
   * A PROP AND NOT A CLIENT READ. It decides whether a stale marker ends this session, so
   * it must not be a value the browser can choose — and the session object auth-js keeps in
   * `localStorage` is exactly that. `null` where GoTrue did not send one, which
   * `inheritedActivity` treats as "cannot tell" and falls back to the old, conservative
   * answer for.
   */
  sessionStartedAt?: string | null
}) {
  /** null when not warning; otherwise whole seconds left. */
  const [secondsLeft, setSecondsLeft] = useState<number | null>(null)

  const lastActivity = useRef(0)
  const lastWrite = useRef(0)
  /** The sign-out must happen once, even though the tick keeps firing while it awaits. */
  const firing = useRef(false)
  /**
   * While the warning is up, ambient activity does NOT dismiss it — only the button does.
   * A dialog is modal, so a stray click landing on the scrim would otherwise reset the
   * timer without the member having seen anything, and they would be signed out later
   * with no warning at all. Typing keeps the warning away in the first place, since
   * keydown is activity.
   */
  const warning = useRef(false)

  const signOutNow = useCallback(async () => {
    if (firing.current) return
    firing.current = true

    const supabase = createClient()
    // `'local'`, not the default `'global'`: this browser's session is the one that went
    // idle. Their phone should not be signed out because a laptop tab was left open.
    await supabase.auth.signOut({ scope: 'local' })

    // DROP THIS SESSION'S MARKER. Without it the sign-out is unrecoverable: the marker is
    // `IDLE_LIMIT_MINUTES` old by definition, it survives the redirect, and the first page
    // the member reaches after signing back in adopts it and expires on its first tick.
    // `inheritedActivity` refuses an expired marker as well — belt and braces, because
    // this call cannot run when the browser is simply closed and that path leaves one too.
    clearIdleActivity()

    try {
      localStorage.setItem(SIGNED_OUT_KEY, String(Date.now()))
    } catch {
      // Private mode, or storage full. The redirect below is what matters.
    }

    // Come back to where they were. `safeNext` on the login page validates it, so a path
    // is all that is being trusted here.
    const returnTo = window.location.pathname + window.location.search
    const url = `/login?error=${encodeURIComponent(TIMEOUT_NOTICE)}&next=${encodeURIComponent(returnTo)}`

    // A FULL DOCUMENT LOAD, not router.replace(). Next's client cache holds rendered RSC
    // payloads for routes already visited, and the React tree in memory still holds the
    // family's data — a soft navigation leaves both intact, so Back or a link could show
    // a signed-in page after the sign-out. `replace` so Back does not return here.
    window.location.replace(url)
  }, [])

  useEffect(() => {
    // Mount time counts as activity: the page has just been rendered for someone.
    const now = Date.now()
    lastActivity.current = now
    lastWrite.current = now

    // ── WHAT THE MARKER LEFT BEHIND MEANS, AND WHAT TO DO ABOUT IT ───────────────────
    // Three answers, and the middle one is what makes this work on a phone at all: a tab
    // opened while another has been idle for nine minutes should INHERIT that clock; a
    // marker this session wrote and then left to go stale means the page was evicted and
    // nobody came back inside the window, which is a sign-out; and anything older than the
    // session itself is residue that must decide nothing. `inheritedActivity` is where that
    // judgement lives and why.
    //
    // `expired` returns immediately — `signOutNow` navigates, so there is nothing for this
    // effect to go on and set up.
    let expiredOnMount = false
    try {
      const stored = inheritedActivity(
        localStorage.getItem(ACTIVITY_KEY), now, sessionStartMs(sessionStartedAt),
      )
      if (stored.kind === 'adopt') {
        lastActivity.current = stored.at
      } else if (stored.kind === 'expired') {
        expiredOnMount = true
      } else {
        // STARTING THIS TAB'S OWN CLOCK, so record that a signed-in page exists NOW. A
        // member who loads a page and reads it without touching anything otherwise leaves
        // no trace at all, and the next load after an eviction has nothing to measure
        // against. Only in this branch: writing after adopting would overwrite the older
        // marker this tab was supposed to inherit.
        markIdleActivity(now)
      }
    } catch {
      // Ignore — an unreadable store just means this tab times itself.
    }
    if (expiredOnMount) {
      signOutNow()
      return
    }

    const markActive = () => {
      if (warning.current) return
      const at = Date.now()
      lastActivity.current = at
      if (at - lastWrite.current >= WRITE_THROTTLE_MS) {
        lastWrite.current = at
        try { localStorage.setItem(ACTIVITY_KEY, String(at)) } catch { /* see above */ }
      }
    }

    // `storage` fires in the OTHER tabs, which is exactly the direction needed.
    const onStorage = (e: StorageEvent) => {
      if (e.key === SIGNED_OUT_KEY && e.newValue) {
        // Another tab timed out and revoked the session this tab is also using.
        signOutNow()
        return
      }
      if (e.key !== ACTIVITY_KEY || !e.newValue) return
      const at = Number(e.newValue)
      if (Number.isFinite(at) && at > lastActivity.current) {
        lastActivity.current = at
        warning.current = false
        setSecondsLeft(null)
      }
    }

    /**
     * ── COMING BACK TO A SUSPENDED TAB ─────────────────────────────────────────────
     * Not activity, and it deliberately does not mark any: somebody switching back to a
     * tab is not somebody who has been at the keyboard for the last two hours. All this
     * does is ask the question the interval could not ask while the tab was frozen.
     *
     * IT IS NOT REDUNDANT WITH THE INTERVAL. iOS suspends JavaScript in a background tab
     * outright, and a back-forward-cache restore resumes a page whose timers may not have
     * been re-armed — so on a phone this is frequently the only thing that runs. Where the
     * interval does resume it would reach the same answer within a second, and this makes
     * the sign-out immediate rather than a beat late on the screen the member is looking
     * at.
     *
     * It reads the SHARED marker as well as this tab's own ref, because another tab may
     * have been the active one while this was frozen and `storage` events do not fire in a
     * suspended document.
     */
    const recheck = () => {
      if (document.visibilityState === 'hidden') return
      let at = lastActivity.current
      try {
        const shared = Number(localStorage.getItem(ACTIVITY_KEY))
        if (Number.isFinite(shared) && shared > at) at = shared
      } catch {
        // See above — this tab's own ref is the fallback and is always usable.
      }
      lastActivity.current = at
      const state = idlePhase(Date.now() - at)
      if (state.phase === 'expired') {
        signOutNow()
        return
      }
      if (state.phase === 'warn') {
        warning.current = true
        setSecondsLeft(state.secondsLeft)
      } else {
        warning.current = false
        setSecondsLeft(null)
      }
    }

    for (const type of ACTIVITY_EVENTS) {
      // Passive: none of these handlers calls preventDefault, and saying so keeps wheel
      // and touchstart off the blocking path.
      window.addEventListener(type, markActive, { passive: true })
    }
    window.addEventListener('storage', onStorage)
    document.addEventListener('visibilitychange', recheck)
    window.addEventListener('focus', recheck)
    // `pageshow` rather than `load`: it fires on a back-forward-cache restore too, which is
    // the one resumption `visibilitychange` can miss.
    window.addEventListener('pageshow', recheck)

    const id = setInterval(() => {
      // Wall clock against a marker, not a decrementing countdown: a laptop that slept
      // through the window wakes up already expired rather than resuming with time left.
      const state = idlePhase(Date.now() - lastActivity.current)

      if (state.phase === 'expired') {
        signOutNow()
        return
      }
      if (state.phase === 'warn') {
        warning.current = true
        setSecondsLeft(state.secondsLeft)
      }
    }, TICK_MS)

    return () => {
      clearInterval(id)
      for (const type of ACTIVITY_EVENTS) window.removeEventListener(type, markActive)
      window.removeEventListener('storage', onStorage)
      document.removeEventListener('visibilitychange', recheck)
      window.removeEventListener('focus', recheck)
      window.removeEventListener('pageshow', recheck)
    }
  }, [signOutNow, sessionStartedAt])

  const staySignedIn = () => {
    const at = Date.now()
    warning.current = false
    lastActivity.current = at
    lastWrite.current = at
    setSecondsLeft(null)
    // Tell the other tabs too, or the next one to tick will sign everybody out.
    try { localStorage.setItem(ACTIVITY_KEY, String(at)) } catch { /* see above */ }
  }

  return (
    <Dialog
      open={secondsLeft !== null}
      onClose={staySignedIn}
      title="Still there?"
      description="You have been inactive for a while, so we are about to sign you out."
    >
      <div className="space-y-4">
        <div className="flex items-center gap-3 rounded-lg border bg-muted/40 px-3 py-2.5 text-sm">
          <Clock className="h-4 w-4 shrink-0 text-brand-accent" aria-hidden="true" />
          <p>
            Signing out in{' '}
            <span className="font-semibold tabular-nums">{secondsLeft ?? 0}</span>
            {secondsLeft === 1 ? ' second' : ' seconds'}.
          </p>
        </div>
        <p className="text-sm text-muted-foreground">
          Anything you have typed and not saved will be lost, so finish up or carry on now.
        </p>
        <Button size="sm" className="w-full" onClick={staySignedIn}>
          I&rsquo;m still here
        </Button>
      </div>
    </Dialog>
  )
}
