'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { Clock } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import {
  ACTIVITY_KEY,
  clearIdleActivity,
  idlePhase,
  inheritedActivity,
  SIGNED_OUT_KEY,
  TICK_MS,
  TIMEOUT_NOTICE,
  WRITE_THROTTLE_MS,
} from '@/lib/idle-timeout'
import { Button } from '@/components/ui/button'
import { Dialog } from '@/components/ui/dialog'

/**
 * Signs a member out after a period with no keyboard or pointer activity and sends them to
 * the login screen. Mounted once, by `app/(protected)/layout.tsx`, and only for a caller
 * who resolved to a user — so it never runs on the marketing site or the auth pages.
 *
 * WHY THIS IS NOT A CONFIG SETTING. `[auth.sessions] inactivity_timeout` in
 * `supabase/config.toml` looks like the same feature and cannot replace it:
 *
 *   * GoTrue measures inactivity as time since the session was last REFRESHED, and a
 *     client with `autoRefreshToken` on refreshes on a timer whether or not anybody is
 *     at the keyboard. So an open tab keeps its session fresh indefinitely and that
 *     setting never fires for the case this component exists for. Measured, not
 *     reasoned — see the note beside the setting.
 *   * It cannot navigate anybody. The session goes invalid and the tab keeps rendering
 *     the page it already has until something fails — which is the opposite of
 *     "return them to the login screen".
 *
 * The two are complements, not alternatives: this covers a human who walked away from an
 * open tab; the setting covers a browser that is not running at all.
 *
 * So the timer lives here, and it is a real sign-out rather than a redirect: when it
 * fires it calls `signOut({ scope: 'local' })`, which revokes this session server-side.
 * The cookie is not merely deleted.
 *
 * WHAT IT DOES NOT COVER, so nobody reads it as more than it is. It measures idleness
 * inside a loaded page. Close the tab and come back tomorrow and the session is still
 * valid, because nothing was running to time it out — that is the half `inactivity_timeout`
 * covers. This closes the case it is aimed at: a signed-in tab left unattended on a shared
 * or visible screen.
 */

/**
 * The durations, the storage keys and the active/warn/expired boundary all live in
 * `lib/idle-timeout.ts` — including `IDLE_LIMIT_MS`, which is the one number anybody
 * changing this feature is looking for.
 */

/**
 * Pointer and keyboard only, deliberately. `mousemove` and `scroll` are generated by
 * momentum scrolling, by a nudged desk and by an animated page, so including them makes
 * the timeout unreliable in the one direction that matters — never firing. A message
 * arriving in a chat room is not activity either: the point is somebody at the keyboard.
 */
const ACTIVITY_EVENTS = ['pointerdown', 'keydown', 'touchstart', 'wheel'] as const

export function IdleTimeout() {
  /** null when not warning; otherwise whole seconds left. */
  const [secondsLeft, setSecondsLeft] = useState<number | null>(null)

  const lastActivity = useRef(0)
  const lastWrite = useRef(0)
  /** The sign-out must happen once, even though the tick keeps firing while it awaits. */
  const firing = useRef(false)
  /**
   * While the warning is up, ambient activity does NOT dismiss it — only the button does.
   * A dialog is modal, so a stray click landing on the scrim would otherwise reset the
   * timer without the member having seen anything, and they would be signed out later
   * with no warning at all. Typing keeps the warning away in the first place, since
   * keydown is activity.
   */
  const warning = useRef(false)

  const signOutNow = useCallback(async () => {
    if (firing.current) return
    firing.current = true

    const supabase = createClient()
    // `'local'`, not the default `'global'`: this browser's session is the one that went
    // idle. Their phone should not be signed out because a laptop tab was left open.
    await supabase.auth.signOut({ scope: 'local' })

    // DROP THIS SESSION'S MARKER. Without it the sign-out is unrecoverable: the marker is
    // 75 minutes old by definition, it survives the redirect, and the first signed-in page
    // the member reaches after signing back in adopts it and expires on its first tick.
    // `inheritedActivity` refuses an expired marker as well — belt and braces, because
    // this call cannot run when the browser is simply closed and that path leaves one too.
    clearIdleActivity()

    try {
      localStorage.setItem(SIGNED_OUT_KEY, String(Date.now()))
    } catch {
      // Private mode, or storage full. The redirect below is what matters.
    }

    // Come back to where they were. `safeNext` on the login page validates it, so a path
    // is all that is being trusted here.
    const returnTo = window.location.pathname + window.location.search
    const url = `/login?error=${encodeURIComponent(TIMEOUT_NOTICE)}&next=${encodeURIComponent(returnTo)}`

    // A FULL DOCUMENT LOAD, not router.replace(). Next's client cache holds rendered RSC
    // payloads for routes already visited, and the React tree in memory still holds the
    // family's data — a soft navigation leaves both intact, so Back or a link could show
    // a signed-in page after the sign-out. `replace` so Back does not return here.
    window.location.replace(url)
  }, [])

  useEffect(() => {
    // Mount time counts as activity: the page has just been rendered for someone.
    const now = Date.now()
    lastActivity.current = now
    lastWrite.current = now

    // A tab opened while another has been idle for nine minutes should inherit that, not
    // reset it — but only from a marker that could still belong to a live tab.
    // `inheritedActivity` is where that judgement lives, and why: an expired marker is
    // residue from a session that has already ended, and adopting it signs the member out
    // one tick after they sign back in.
    try {
      const stored = inheritedActivity(localStorage.getItem(ACTIVITY_KEY), now)
      if (stored !== null) lastActivity.current = stored
    } catch {
      // Ignore — an unreadable store just means this tab times itself.
    }

    const markActive = () => {
      if (warning.current) return
      const at = Date.now()
      lastActivity.current = at
      if (at - lastWrite.current >= WRITE_THROTTLE_MS) {
        lastWrite.current = at
        try { localStorage.setItem(ACTIVITY_KEY, String(at)) } catch { /* see above */ }
      }
    }

    // `storage` fires in the OTHER tabs, which is exactly the direction needed.
    const onStorage = (e: StorageEvent) => {
      if (e.key === SIGNED_OUT_KEY && e.newValue) {
        // Another tab timed out and revoked the session this tab is also using.
        signOutNow()
        return
      }
      if (e.key !== ACTIVITY_KEY || !e.newValue) return
      const at = Number(e.newValue)
      if (Number.isFinite(at) && at > lastActivity.current) {
        lastActivity.current = at
        warning.current = false
        setSecondsLeft(null)
      }
    }

    for (const type of ACTIVITY_EVENTS) {
      // Passive: none of these handlers calls preventDefault, and saying so keeps wheel
      // and touchstart off the blocking path.
      window.addEventListener(type, markActive, { passive: true })
    }
    window.addEventListener('storage', onStorage)

    const id = setInterval(() => {
      // Wall clock against a marker, not a decrementing countdown: a laptop that slept
      // through the window wakes up already expired rather than resuming with time left.
      const state = idlePhase(Date.now() - lastActivity.current)

      if (state.phase === 'expired') {
        signOutNow()
        return
      }
      if (state.phase === 'warn') {
        warning.current = true
        setSecondsLeft(state.secondsLeft)
      }
    }, TICK_MS)

    return () => {
      clearInterval(id)
      for (const type of ACTIVITY_EVENTS) window.removeEventListener(type, markActive)
      window.removeEventListener('storage', onStorage)
    }
  }, [signOutNow])

  const staySignedIn = () => {
    const at = Date.now()
    warning.current = false
    lastActivity.current = at
    lastWrite.current = at
    setSecondsLeft(null)
    // Tell the other tabs too, or the next one to tick will sign everybody out.
    try { localStorage.setItem(ACTIVITY_KEY, String(at)) } catch { /* see above */ }
  }

  return (
    <Dialog
      open={secondsLeft !== null}
      onClose={staySignedIn}
      title="Still there?"
      description="You have been inactive for a while, so we are about to sign you out."
    >
      <div className="space-y-4">
        <div className="flex items-center gap-3 rounded-lg border bg-muted/40 px-3 py-2.5 text-sm">
          <Clock className="h-4 w-4 shrink-0 text-brand-accent" aria-hidden="true" />
          <p>
            Signing out in{' '}
            <span className="font-semibold tabular-nums">{secondsLeft ?? 0}</span>
            {secondsLeft === 1 ? ' second' : ' seconds'}.
          </p>
        </div>
        <p className="text-sm text-muted-foreground">
          Anything you have typed and not saved will be lost, so finish up or carry on now.
        </p>
        <Button size="sm" className="w-full" onClick={staySignedIn}>
          I&rsquo;m still here
        </Button>
      </div>
    </Dialog>
  )
}
