-- ============================================================================
-- Authorization rebuild, pass 4 of 4: retire the legacy admin flags.
--
-- SUPERSEDED BY 20260618000003_strip_legacy_admin_policies.sql — INTENTIONALLY
-- A NO-OP.
--
-- WHAT THIS FILE USED TO DO
--   ALTER TABLE public.people DROP COLUMN IF EXISTS is_admin;
--   ALTER TABLE public.people DROP COLUMN IF EXISTS can_approve;
--
-- WHY IT IS EMPTY NOW
--   The drop cannot succeed at this point in the chain. 20260618000001 composed
--   the permission check onto every existing policy while PRESERVING each
--   policy's original expression — and ~64 of those expressions contain
--       EXISTS (SELECT 1 FROM people WHERE ... AND is_admin = true ...)
--   so ~64 `perm:` policies depend on people.is_admin by the time this runs.
--   Postgres refuses the drop:
--
--     ERROR: cannot drop column is_admin of table people because other objects
--     depend on it (SQLSTATE 2BP01)
--
--   That is not a hypothetical. Applying this chain to an empty database fails
--   here, which is why `supabase db reset` / `supabase start` could not build
--   the schema from scratch until this file was emptied.
--
--   20260618000003 fixes the ordering properly: it first rewrites every
--   `EXISTS (... is_admin ...)` sub-expression to TRUE (leaving family scoping
--   byte-identical, with the swept-on permission check becoming the authority),
--   and only THEN drops both columns — with the same "no orphaned admin" guard
--   this file carried. It is a strict superset of this migration.
--
-- DO NOT restore the statements here. Dropping the columns belongs after the
-- policy rewrite, and 20260618000003 is where that happens.
--
-- Kept as an empty, applied migration rather than deleted so the ledger of
-- already-migrated databases stays intact.
-- ============================================================================

-- (no-op)
